name: deploy
on: 
  pull_request: 
    branches: [ master ] 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.3.0
        with: 
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Publish 
        run: dotnet publish ./HouseKeeperApi/HouseKeeperApi.csproj  -c Release -o ${{ env.DOTNET_ROOT }}/api
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.0
        with: 
          name: Api artifact
          path: ${{ env.DOTNET_ROOT }}/api
          
  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    environment: 
      name: 'Dev'
      url: ${{ secrets.deploy-to-azure.outputs.webapp-url }}
    steps:      
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.8
        with: 
          name: Api artifact
      - name: Azure WebApp
        id: deploy-to-azure
        uses: Azure/webapps-deploy@v2.2.12
        with:
          app-name: 'housekeeper-dev'
          publish-profile: ${{ secrets.PUBLISH_PROFILE_DEV }}
