name: CI
on: 
  pull_request: 
    branches: [ master ] 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.3.0
        with: 
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Publish 
        run: dotnet publish ./HouseKeeperApi/HouseKeeperApi.csproj  -c Release -o ${{ env.DOTNET_ROOT }}/api
  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    steps: